const barsak = {
  Gender: '',
  PhoneNumber: '',
  Birthday: '',
  RecordDate: '',
  IdentityNo: '',
  ProtocolNo: '',
  FullName: '',
  Age: '',
  PatientId: '',
  FormName: 'Barsak Yönetim Form',
  path: '/form/barsak-yonetim',
  FormInsertDate: '',
  FormUpdateDate: '',
  formType: '',
  q1: '',
  'q1-comment': '',
  q2: '',
  q3: '',
  q4: '',
  q5: '',
  'q5-lavman-no': '',
  'q5-lavman-vol': '',
  'q6-date': '',
  'q6-ydgb': '',
  'q6-1': '',
  'q6-1-comment': '',
  'q6-2': '',
  'q6-3': '',
  'q6-plan': '',
  q7: '',
  'q7-1': '',
  'q7-2': '',
  'q7-3': '',
  'q7-4': '',
  'q7-5': '',
  'q7-6': '',
  'q7-7': '',
  'q7-8': '',
  'q7-9-enough': '',
  'q7-9-not-enough': '',
  'q7-10': '',
  'q7-11': '',
  'q7-12': '',
  'q7-13-plan': '',
};

export default barsak;
