// eslint-disable-next-line @typescript-eslint/no-unused-vars
const KabizlikFormGroup = {
  Gender: '',
  PhoneNumber: '',
  Birthday: '',
  RecordDate: '',
  IdentityNo: '',
  ProtocolNo: '',
  FullName: '',
  Age: '',
  PatientId: '',
  FormName: 'Kabızlık Inkotinans Form',
  path: '/form/kabizlik-form',
  FormInsertDate: '',
  FormUpdateDate: '',
  formType: '',
  q1: '', // 1. Çocuğunuz kaç günde bir büyük tuvaletini yapıyor?
  q2: '', // 2. Büyük tuvaletini yapması için uyarı veya lavman yapmanız gerekiyor mu?
  'bristol-deger': '',
  'q3-1': '', // - Haftada iki ya da daha az dışkılama
  'q3-2': '', // - Aşırı dışkı birikmesi öyküsü
  'q3-3': '', // - Ağrılı ve sert dışkılama
  'q3-4': '', // - Büyük çaplı dışkılama
  'q3-5': '', // - Rektumda büyük dışkı kitlesinin bulunması
  'q3-6': '', // - Haftada en az bir kere dışkı kaçırma öyküsü
  'q3-7': '', // - Tuvaleti bile tıkayabileGek kadar geniş çaplı dışkılama öyküsü
  'q3-8': '', // - Kabızlık Skoru (Roma IV)
  q4: '',
  'q4-age': '',
  q5: '',
  q6: '',
  'q6-other': '',
  q7: '',
  q8: '',
  q9: '',
  q10: '',
  q11: '',
  'q11-1': '',
  q12: '',
  q13: '',
  'q13-1': '',
  q14: '',
  q15: '',
  'q16-laksatif': '',
  'q16-laksatif-1': '',
  'q16-laksatif-1-duration': '',
  'q16-lavman': '',
  'q16-lavman-1': '',
  'q16-treatment': '',
  q17: '',
  q18: '',
  q19: '',
  q20: '',
  q21: '',
  q22: '',
  'q22-1': '',
  'q22-comment': '',
  'q23-length': '',
  'q23-length-persentil': '',
  'q23-weight': '',
  'q23-weight-persentil': '',
  q24: '',
  q25: '',
  q26: '',
  q27: '',
  q28: '',
  q29: '',
  q30: '',
  q31: '',
  q32: '',
  q33: '',
  q34: '',
  q35: '',
  q36: '',
  q37: '',
  q38: '',
  q39: '',
  q40: '',
  q41: '',
  q42: '',
  q43: '',
  'q43-comment': '',
  q44: '',
  'q44-comment': '',
  q45: '',
  q46: '',
  q47: '',
  q48: '',
  q49: '',
  q50: '',
  q51: '',
  'q51-1': '',
  'q51-1-comment': '',
  'q52-rektopelvik-oran': '',
  'q52-rektopelvik-oran-1': '',
  q53: '',
  'q53-comment': '',
  q54: '',
  'q54-1': '',
};

export default KabizlikFormGroup;
