const kolorektal = {
  Gender: '',
  PhoneNumber: '',
  Birthday: '',
  RecordDate: '',
  IdentityNo: '',
  ProtocolNo: '',
  FullName: '',
  Age: '',
  PatientId: '',
  FormName: 'Kolorektal Hasta Form',
  path: '/form/kolorektal-form',
  formType: '',
  FormInsertDate: '',
  FormUpdateDate: '',
  history: '',
  'physical-examination': '',
  'surgical-history': '',
  'medical-history': '',
  feces: '',
  pee: '',
  'spine-condition': '',
};

export default kolorektal;
