const laksatif = {
  Gender: '',
  PhoneNumber: '',
  Birthday: '',
  RecordDate: '',
  IdentityNo: '',
  ProtocolNo: '',
  FullName: '',
  Age: '',
  PatientId: '',
  FormName: 'Laksatif Günlüğü',
  path: '/form/laksatif-form',
  formType: '',
  'laxative-type': '',
  'laxative-date': '',
  'monday-dose': '',
  'monday-defecation-status': '',
  'monday-fecal-incontinence': '',
  'monday-need-enema': '',
  'tuesday-dose': '',
  'tuesday-defecation-status': '',
  'tuesday-fecal-incontinence': '',
  'tuesday-need-enema': '',
  'wednesday-dose': '',
  'wednesday-defecation-status': '',
  'wednesday-fecal-incontinence': '',
  'wednesday-need-enema': '',
  'thursday-dose': '',
  'thursday-defecation-status': '',
  'thursday-fecal-incontinence': '',
  'thursday-need-enema': '',
  'friday-dose': '',
  'friday-defecation-status': '',
  'friday-fecal-incontinence': '',
  'friday-need-enema': '',
  'saturday-dose': '',
  'saturday-defecation-status': '',
  'saturday-fecal-incontinence': '',
  'saturday-need-enema': '',
  'sunday-dose': '',
  'sunday-defecation-status': '',
  'sunday-fecal-incontinence': '',
  'sunday-need-enema': '',
};

export default laksatif;
